'use client';
import { useState } from 'react';
import type { Product } from '@/lib/db';

const blank={name:'',slug:'',category:'Men',description:'',price:0,currency:'NGN',image:'/images/look1.jpg',badge:'',available:true,featured:false,sort_order:0};

export function LoginForm(){
 const [email,setEmail]=useState('admin@odera.luxe'); const [password,setPassword]=useState(''); const [error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setError('');const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(r.ok) location.href='/admin'; else setError((await r.json()).error||'Login failed');}
 return <main className="login"><form className="loginBox" onSubmit={submit}><div className="logo">ODERA<small>LUXE</small></div><div className="eyebrow" style={{marginTop:30}}>Private Studio</div><h1 className="serif" style={{fontWeight:500}}>Admin login</h1><div className="field"><label>Email</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email" /></div><div className="field" style={{marginTop:15}}><label>Password</label><input value={password} onChange={e=>setPassword(e.target.value)} type="password" /></div>{error&&<div className="error">{error}</div>}<button className="adminBtn" style={{marginTop:20,width:'100%'}}>Enter Studio</button></form></main>
}

export function AdminDashboard({initialProducts}:{initialProducts:Product[]}){
 const [products,setProducts]=useState(initialProducts); const [editing,setEditing]=useState<Partial<Product>|null>(null); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
 const start=(p?:Product)=>setEditing(p?{...p}:{...blank});
 async function save(){if(!editing?.name)return;setSaving(true);const isNew=!editing.id;const r=await fetch(isNew?'/api/admin/products':`/api/admin/products/${editing.id}`,{method:isNew?'POST':'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing)});if(r.ok){location.reload()}else setMessage((await r.json()).error||'Could not save');setSaving(false)}
 async function del(id:number){if(!confirm('Delete this product?'))return;const r=await fetch(`/api/admin/products/${id}`,{method:'DELETE'});if(r.ok)setProducts(p=>p.filter(x=>x.id!==id));}
 async function logout(){await fetch('/api/admin/logout',{method:'POST'});location.href='/admin/login'}
 return <main className="adminShell"><header className="adminNav"><div className="logo">ODERA<small>LUXE</small></div><div style={{display:'flex',gap:10}}><button className="adminBtn" onClick={()=>start()}>+ Add Product</button><button className="adminBtn secondary" onClick={logout}>Logout</button></div></header><div className="adminMain"><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',marginBottom:20}}><div><div className="eyebrow">Content Studio</div><h1 className="serif" style={{fontWeight:500,fontSize:48,margin:'10px 0'}}>Products</h1><p style={{color:'#aaa',fontSize:13}}>Manage prices, descriptions, images, availability and featured pieces.</p></div></div>{editing&&<section className="adminForm" style={{marginBottom:25}}><div className="eyebrow">{editing.id?'Edit product':'New product'}</div><div className="formGrid" style={{marginTop:20}}>{[['name','Name'],['slug','Slug'],['category','Category'],['price','Price'],['currency','Currency'],['image','Image path'],['badge','Badge'],['sort_order','Sort order']].map(([key,label])=><div className="field" key={key}><label>{label}</label><input value={String((editing as any)[key]??'')} onChange={e=>setEditing({...editing,[key]:key==='price'||key==='sort_order'?Number(e.target.value):e.target.value})}/></div>)}<div className="field full"><label>Description</label><textarea value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})}/></div><div className="check"><input type="checkbox" checked={!!editing.available} onChange={e=>setEditing({...editing,available:e.target.checked})}/> Available for WhatsApp store</div><div className="check"><input type="checkbox" checked={!!editing.featured} onChange={e=>setEditing({...editing,featured:e.target.checked})}/> Featured on homepage</div></div>{message&&<div className="error">{message}</div>}<div className="adminActions"><button className="adminBtn" onClick={save} disabled={saving}>{saving?'Saving…':'Save product'}</button><button className="adminBtn secondary" onClick={()=>setEditing(null)}>Cancel</button></div></section>}
 <section className="adminTable"><div className="tableWrap"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Status</th><th>Featured</th><th></th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><strong>{p.name}</strong><br/><span style={{color:'#777'}}>{p.slug}</span></td><td>{p.category}</td><td>₦{p.price.toLocaleString()}</td><td>{p.available?'Available':'Hidden'}</td><td>{p.featured?'Yes':'No'}</td><td style={{whiteSpace:'nowrap'}}><button className="adminBtn secondary" onClick={()=>start(p)}>Edit</button> <button className="adminBtn secondary" onClick={()=>del(p.id)}>Delete</button></td></tr>)}</tbody></table></div></section></div></main>
}
